var myString = "This is an example of a string";
console.log(myString);
console.log("We can also output strings right to the console");
console.log("just make sure you use double quotes \" or'");
console.log('this is an example of using a \'');
var firsthalf = "strings can be ";
var secondhalf = 'concatenated by using +';
console.log(firsthalf + secondhalf);
console.log("in the above lines i used ");
console.log("a \\ before some characters");
console.log("the \\ is called am escape character");
console.log("there ar many of these");
console.log("the \\n escape charcter prints");
console.log("a new line");
var manyLines = "Every\nword\nwill\nbe\non\na\nnew\nline"
console.log(manyLines);
var Charcount = secondhalf.length;
console.log("secondHalf has " + Charcount + " characters");
console.log("notice that spaces count as characters");
console.log("The position of a character in a sting is");
console.log("called the index");
var indexExample = "abcdefghijklmnopqrstuvwxyz";
console.log("indexOf will give the index for the");
console.log("first occurance of a group of characters");
console.log("the index of de is " + indexExample.indexOf("de") );
console.log("this is very important so i will scream at you");
var yelling = "computers start counting at o not 1";
console.log(yelling.toUpperCase());
console.log("Did we change yelling to upper case?");
console.log(yelling);
console.log("what if we wanted to");
yelling = yelling.toUpperCase();
console.log(yelling);